=== sandrina-cunha-tic/212_xml/editorial.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="text" type="xsd:string"/>
	<xsd:element name="page">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="entete"/>
				<xsd:element name="corps"/>
				<xsd:element name="pied"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="entete">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="titre"/>
				<xsd:element name="navigation"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="titre">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="navigation">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="liste"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="liste">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="lien"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="lien">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="sousliste"/>
			</xsd:sequence>
			<xsd:attribute name="nom" type="xsd:string" use="required"/>
			<xsd:attribute name="lien" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="sousliste">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="souslien"/>
				<xsd:element name="souslien2"/>
				<xsd:element name="souslien3"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="souslien">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string" use="required"/>
			<xsd:attribute name="lien" type="xsd:string" use="required"/>		
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="souslien2">
		<xsd:complexType>
			<xsd:attribute name="nom_1" type="xsd:string" use="required"/>
			<xsd:attribute name="lien1" type="xsd:string" use="required"/>		
		</xsd:complexType>
	</xsd:element>	

	<xsd:element name="souslien3">
		<xsd:complexType>
			<xsd:attribute name="nom_2" type="xsd:string" use="required"/>
			<xsd:attribute name="lien2" type="xsd:string" use="required"/>		
		</xsd:complexType>
	</xsd:element>	

	<xsd:element name="corps">
		<xsd:complexType>

			<xsd:sequence>
				<xsd:element name="introduction"/>
				<xsd:element name="articles"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="introduction">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="text"/>
			</xsd:sequence>
			<xsd:attribute name="nom" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="membres">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="membre1"/>
				<xsd:element name="membre2"/>
				<xsd:element name="membre3"/>
				<xsd:element name="membre4"/>
				<xsd:element name="membre5"/>
				<xsd:element name="membre6"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="membre1">
		<xsd:complexType>
				<xsd:attribute name="nom" use="required" type="xsd:string"/>
				<xsd:attribute name="prenom" use="required" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="membre2">
		<xsd:complexType>
				<xsd:attribute name="nom" use="required" type="xsd:string"/>
				<xsd:attribute name="prenom" use="required" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="membre3">
		<xsd:complexType>
				<xsd:attribute name="nom" use="required" type="xsd:string"/>
				<xsd:attribute name="prenom" use="required" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="membre4">
		<xsd:complexType>
				<xsd:attribute name="nom" use="required" type="xsd:string"/>
				<xsd:attribute name="prenom" use="required" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="membre5">
		<xsd:complexType>
				<xsd:attribute name="nom" use="required" type="xsd:string"/>
				<xsd:attribute name="prenom" use="required" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="membre6">
		<xsd:complexType>
				<xsd:attribute name="nom" use="required" type="xsd:string"/>
				<xsd:attribute name="prenom" use="required" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="pied">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="text"/>
				<xsd:element name="lien_footer"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="lien_footer">
		<xsd:complexType>
				<xsd:attribute name="nom" use="required" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== sandrina-cunha-tic/212_xml/editorial.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet href="editorial.xsl" type="text/xsl"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editorial.xsd">
	<entete>
		<titre nom="Editorial" />
		<navigation>
			<liste>
				<lien nom="Accueil" lien="index.xml">
					<sousliste>
						<souslien nom="Origines" lien="origine.xml" />
						<souslien2 nom_1="Atouts" lien1="atout.xml" />
						<souslien3 nom_2="Freins" lien2="frein.xml" />
					</sousliste>
				</lien>
				<lien nom="actuelle" lien="actuelle.xml">
					<sousliste>
						<souslien nom="Place" lien="place.xml" />
						<souslien2 nom_1="Ajax" lien1="ajax.xml" />
						<souslien3 nom_2="Application" lien2="app.xml" />
					</sousliste>
				</lien>
				<lien nom="futur" lien="futur.xml">
					<sousliste>
						<souslien nom="Web 3.0" lien="web.xml" />
						<souslien2 nom_1="Evolutions" lien1="evol.xml" />
						<souslien3 nom_2="XXIème" lien2="siecle.xml" />
					</sousliste>
				</lien>
				<lien nom="Conclusion" lien="conc.xml">
					<sousliste>
						<souslien nom="Liens 1" lien="conc1.xml" />
						<souslien2 nom_1="Lien 2" lien1="conc2.xml" />
						<souslien3 nom_2="Lien 3" lien2="conc3.xml" />
					</sousliste>
				</lien>
			</liste>
		</navigation>
	</entete>
	<corps>
		<introduction nom="Pourquoi un éditorial">
			<text>On commence à entendre beaucoup parler du langage xml depuis quelques années.
				Le web étant aussi en perpétuelle évolution, le web 3.0 se profile avec des métamorphoses importantes
				au niveau des applications pratiques. Le langage XML et ses dérivés sont-ils juste un effet de mode
				ou vont-ils prendre une place de plus en plus importante dans les nouvelles évolutions de l'Internet ?</text>
		</introduction>
		<membres>
			<membre1 nom="MATHIEU" prenom="Mickael">On commence à entendre beaucoup parler du langage xml depuis quelques années.
				Le web étant aussi en perpétuelle évolution, le web 3.0 se profile avec des métamorphoses importantes
				au niveau des applications pratiques. Le langage XML et ses dérivés sont-ils juste un effet de mode
				ou vont-ils prendre une place de plus en plus importante dans les nouvelles évolutions de l'Internet ?</membre1>
			<membre2 nom="Champey" prenom="Elsa">On commence à entendre beaucoup parler du langage xml depuis quelques années.
				Le web étant aussi en perpétuelle évolution, le web 3.0 se profile avec des métamorphoses importantes
				au niveau des applications pratiques. Le langage XML et ses dérivés sont-ils juste un effet de mode
				ou vont-ils prendre une place de plus en plus importante dans les nouvelles évolutions de l'Internet ?</membre2>
			<membre3 nom="Saghroun" prenom="Yael">On commence à entendre beaucoup parler du langage xml depuis quelques années.
				Le web étant aussi en perpétuelle évolution, le web 3.0 se profile avec des métamorphoses importantes
				au niveau des applications pratiques. Le langage XML et ses dérivés sont-ils juste un effet de mode
				ou vont-ils prendre une place de plus en plus importante dans les nouvelles évolutions de l'Internet ?</membre3>
			<membre4 nom="Cunha" prenom="Sandrina">On commence à entendre beaucoup parler du langage xml depuis quelques années.
				Le web étant aussi en perpétuelle évolution, le web 3.0 se profile avec des métamorphoses importantes
				au niveau des applications pratiques. Le langage XML et ses dérivés sont-ils juste un effet de mode
				ou vont-ils prendre une place de plus en plus importante dans les nouvelles évolutions de l'Internet ?</membre4>
			<membre5 nom="Elefant" prenom="Deborah">On commence à entendre beaucoup parler du langage xml depuis quelques années.
				Le web étant aussi en perpétuelle évolution, le web 3.0 se profile avec des métamorphoses importantes
				au niveau des applications pratiques. Le langage XML et ses dérivés sont-ils juste un effet de mode
				ou vont-ils prendre une place de plus en plus importante dans les nouvelles évolutions de l'Internet ?</membre5>
			<membre6 nom="Ganne" prenom="Ségolène">On commence à entendre beaucoup parler du langage xml depuis quelques années.
				Le web étant aussi en perpétuelle évolution, le web 3.0 se profile avec des métamorphoses importantes
				au niveau des applications pratiques. Le langage XML et ses dérivés sont-ils juste un effet de mode
				ou vont-ils prendre une place de plus en plus importante dans les nouvelles évolutions de l'Internet ?</membre6>
		</membres>
	</corps>
	<pied>
		<text>Le site du groupe7</text>
		<lien_footer nom="Editorial" />
	</pied>
</page>
