=== sandrina-cunha-tic/212_xml/index.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="text" type="xsd:string"/>
	<xsd:element name="pied" type="xsd:string"/>

	<xsd:element name="page">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="entete"/>
				<xsd:element name="corps"/>
				<xsd:element name="pied"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="entete">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="titre"/>
				<xsd:element name="navigation"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="titre">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="navigation">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="liste"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="liste">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="lien_acc"/>
				<xsd:element name="lien"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="lien_acc">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="lien">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="sousliste"/>
			</xsd:sequence>
			<xsd:attribute name="nom" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="sousliste">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="souslien"/>
			</xsd:sequence>
			<xsd:attribute name="nom" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="corps">
		<xsd:complexType>

			<xsd:sequence>
				<xsd:element name="introduction"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="introduction">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="text"/>
			</xsd:sequence>
			<xsd:attribute name="nom" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="lien4">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="souslien1"/>
				<xsd:element name="souslien2"/>
				<xsd:element name="souslien3"/>
			</xsd:sequence>
			<xsd:attribute name="nom" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="lien5">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="souslien1">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="souslien2">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="souslien3">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="souslien4">
		<xsd:complexType>
			<xsd:attribute name="nom" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== sandrina-cunha-tic/212_xml/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet href="index.xsl" type="text/xsl"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
  <entete>
		<titre nom="XML et évolution du Web" />
		<navigation>
			<liste>
				<lien_acc nom="accueil" />
				<lien nom="Origine et but du XML">
					<sousliste>
						<souslien nom="Les origines du xml" />
						<souslien nom_1="Pourquoi le XML ?" />
						<souslien nom_2="les atouts du XML" />
						<souslien nom_3="Un format en vogue" />
					</sousliste>
				</lien>
				<lien nom="Les évolutions du web">
					<sousliste>
						<souslien nom="Web 3.0" />
						<souslien nom_1="Web sémantique" />
						<souslien nom_2="Internet des objets" />
						<souslien nom_3="Internet mobile" />
					</sousliste>
				</lien>
				<lien nom="L’évolution du XML">
					<sousliste>
						<souslien nom="Les freins" />
						<souslien nom_1="La convergence" />
						<souslien nom_2="le langage du XXIème siècle ?" />
					</sousliste>
				</lien>
				<lien_acc nom="Conclusion" />
			</liste>
		</navigation>
	</entete>
	<corps>
		<introduction>
			<text>On commence à entendre beaucoup parler du langage xml depuis quelques années.
				Le web étant aussi en perpétuelle évolution, le web 3.0 se profile avec des métamorphoses importantes
				au niveau des applications pratiques. Le langage XML et ses dérivés sont-ils juste un effet de mode
				ou vont-ils prendre une place de plus en plus importante dans les nouvelles évolutions de l'Internet ?</text>
		</introduction>
	</corps>
	<pied></pied>
</page>

=== sandrina-cunha-tic/212_xml/futur.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet href="actuelle.xsl" type="text/xsl"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
  <entete>
		<titre nom="Futur" />
		<navigation>
			<liste>
				<lien nom="Accueil" lien="index.xml">
					<sousliste>
						<souslien nom="Origines" lien="origine.xml" />
						<souslien2 nom_1="Atouts" lien1="atout.xml" />
						<souslien3 nom_2="Freins" lien2="frein.xml" />
					</sousliste>
				</lien>
				<lien nom="actuelle" lien="actuelle.xml">
					<sousliste>
						<souslien nom="Place" lien="place.xml" />
						<souslien2 nom_1="Ajax" lien1="ajax.xml" />
						<souslien3 nom_2="Application" lien2="app.xml" />
					</sousliste>
				</lien>
				<lien nom="futur" lien="futur.xml">
					<sousliste>
						<souslien nom="Web 3.0" lien="web.xml" />
						<souslien2 nom_1="Evolutions" lien1="evol.xml" />
						<souslien3 nom_2="XXIème" lien2="siecle.xml" />
					</sousliste>
				</lien>
				<lien nom="Conclusion" lien="conc.xml">
					<sousliste>
						<souslien nom="Liens 1" lien="conc1.xml" />
						<souslien2 nom_1="Lien 2" lien1="conc2.xml" />
						<souslien3 nom_2="Lien 3" lien2="conc3.xml" />
					</sousliste>
				</lien>
			</liste>
		</navigation>
	</entete>
	<corps>
		<introduction nom="Avant propos">
			<text>On commence à entendre beaucoup parler du langage xml depuis quelques années, bien qu’il ne soit en réalité pas si nouveau que cela. Il présente des avantages indéniables au niveau de sa modularité, de sa lisibilité et de son universalité.
				Dans le contexte où le web est aussi en perpétuelle évolution, où le web 3.0 se profile avec des métamorphoses importantes au niveau des applications pratiques, le langage XML et ses dérivés sont-ils juste un effet de mode ou vont-ils, comme cela semble probable, prendre une place centrale dans les technologies d’avenir ?</text>
		</introduction>
		<articles>
			<article1 nom="Rappel " nom2="Historique">
				<text>Oui alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants.
					 d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec Oui alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants.
					Oui alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants.</text>
			</article1>
			<article2 nom="Les atouts " nom2="du XML">
				<text>Oui alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants.
					 parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec  Oui alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants.
					Oui alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants  avec des replicants.</text>
			</article2>
			<article3 nom="Les freins " nom2="du XML">
				<text>Oui alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants.
					 parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants.
					Oui alors écoute moi, premièrement, c'est juste une question d'awareness parce que spirituellement, on est tous ensemble, ok ? C'est pour ça que j'ai fait des films avec des replicants  avec des replicants.</text>
			</article3>
		</articles>
	</corps>
	<pied>
		<text_footer>Le site du groupe7</text_footer>
		<lien_footer nom="Editorial" />
	</pied>
</page>
